# Generated by Django 4.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0020_alter_perfildepartamento_sigla"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioComboio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("data_operacao", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enviado", "Enviado"),
                            ("visualizado", "Visualizado"),
                        ],
                        default="enviado",
                        max_length=20,
                    ),
                ),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "comboio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relatorios",
                        to="api.comboio",
                    ),
                ),
                (
                    "delegacia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relatorios_comboio",
                        to="api.delegacia",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relatorios_comboio",
                        to="api.departamento",
                    ),
                ),
                (
                    "operacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relatorios_comboio",
                        to="api.operacao",
                    ),
                ),
                (
                    "policial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatorios_comboio",
                        to="api.policial",
                    ),
                ),
                (
                    "visualizado_por",
                    models.ManyToManyField(
                        blank=True,
                        related_name="relatorios_comboio_visualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório de Comboio",
                "verbose_name_plural": "Relatórios de Comboio",
                "ordering": ["-data_operacao", "-enviado_em"],
            },
        ),
    ]
