# Generated by Django 4.2.7 on 2026-08-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_relatoriocomboio"),
    ]

    operations = [
        migrations.CreateModel(
            name="RosterPolicial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(db_index=True, max_length=8, unique=True),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cargo", models.CharField(blank=True, max_length=100)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Policial do Roster",
                "verbose_name_plural": "Policiais do Roster",
                "ordering": ["nome"],
            },
        ),
    ]
